### ISSUE TITLE
using YAMNET 

### ISSUE THREAD

**Issue by ckswls56** [vohuynh19/react-native-speech-command#1]
Hello! I'm enjoying looking at your code! Do you know how to use YAMNET in REACT NATIVE?

**Comment by vohuynh19** [comment]
The current library does not support to change to YAMNET model.
To use YAMNET model, you need to manually change the native code.
For example: In Android, visit this file `https://github.com/vohuynh19/react-native-speech-command/blob/main/android/src/main/java/com/speechcommand/SpeechCommandModule.kt`. 
Change code:
From `currentModel: String = SPEECH_COMMAND_MODEL `
to `var currentModel: String = YAMNET_MODEL`

**Comment by ckswls56** [comment]
Thank you for your response
